# Generated by Django 5.0.7 on 2024-08-13 04:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='news_tittle', unique=True),
        ),
    ]
